### ISSUE TITLE
Final TODO:

### ISSUE THREAD

**Issue by hrmJ** [hrmJ/100-tapaa-indikoida-topiikkia#35]
- [x] Lähteet
- [x] @smith pois
- [x] taulukon alle kolme päätekijää (?)
- [x] taulukon ylle sen kuvaus
- [x] pitkä lause repertuaarista
- [x] sivunumerot komppaan johdannossa 
- [x] "operationalisoimaan ..." -virke
- [x] Kolmannessa vaiheessa
- [x] nimet pois
- [x] VISK manuaalisesti
- [x] Pitääkö olla jossain viittaus Biberiin? (se oli lähteissä, muttei tekstissä)
- [x] Tekstissä ei myöskään enää ole tätä:  *Juvonen, Riitta, Mikko Virtanen & Eero Voutilainen 2012. Fennistisen tekstilajitutkimuksen suuntia.*
- [x] ajatusviivat
- [x] sivunumerot tänne: *jää kuitenkin huomattava joukko tekstilajeja, joissa tekstin rakennetta voi kuvata ennemmin topiikkipohjaiseksi ja temaattisen sisällön pohjalta rakentuvaksi*
- [x] lähteiden tarkennus tähän: *mitään siitä, millaisessa asemassa kappale hierakkisesti on tekstin kokonaisrakenteen kannalta. (kotimaiset; Smith 2008: 85)*

**Comment by hrmJ** [comment]
@Kirde80 ks. täältä!

**Comment by hrmJ** [comment]
@Kirde80 Kas noin, nyt on kaikki isoimmat jutut hoidettu. Ehditkö kurkkaamaan jossain välissä noita tähän ylle listattuja juttuja (osa niistä ehkä ihan läpihuutokamaa, mutta kuitenkin). Eli pullauta ensin ja sitten siinä ehdotus....docx-tiedostossa edelleen kaikki muutokset

**Comment by hrmJ** [comment]
niin ja siis tietysti ylipäätään muokkaa se mun taulukkokuvaus siihen suuntaan kuin parhaaksi katsot ja silmäile muutenkin.. Mä ehdin hyvin vielä huomenna aamusta tehdä omat loput tarkistukseni

**Comment by Kirde80** [comment]
Jees, heti kun purnasin niin pääsin kuin pääsinkin verkkoon! Laitan sulle
aamuun mennessä paluupostia!

2018-02-07 15:38 GMT+02:00 Juho Härme <notifications@github.com>:

**Comment by hrmJ** [comment]
Kaikki valmista...
